#!/bin/sh
test -z "$V_CONTAINER_NAME" \
  && export V_CONTAINER_NAME="docker-link"

test -S /var/run/docker.sock \
  && echo "Tunneling 'tcp/2375' to '/var/run/docker.sock'" \
  && echo "" \
  && echo "    export DOCKER_HOST=tcp://$V_CONTAINER_NAME:2375" \
  && echo "" \
  && exec socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CLIENT:/var/run/docker.sock

echo "'docker-tunnel-socket' must have access to '/var/run/docker.sock' on the docker host:"
echo ""
echo "    docker run -d --privileged --userns=host \\"
echo "        -v /var/run/docker.sock:/var/run/docker.sock \\"
echo "        --name $V_CONTAINER_NAME $V_CONTAINER_NAME"
echo ""
echo "Then to use the socket, run:"
echo ""
echo "    docker run --rm -it \\"
echo "        --link $V_CONTAINER_NAME --volumes-from $V_CONTAINER_NAME \\"
echo "        $V_CONTAINER_NAME docker ps"
echo ""
echo "or run using '$V_CONTAINER_NAME' as a utility collection:"
echo ""
echo "    docker run --rm -it \\"
echo "        --link $V_CONTAINER_NAME --volumes-from $V_CONTAINER_NAME \\"
echo "        ubuntu:xenial /tools/docker/docker -H tcp://$V_CONTAINER_NAME:2375 ps "
echo ""
exit 1
